### ISSUE TITLE
Gap Adjust Cruise can't switch from steering wheel.

### ISSUE THREAD

**Issue by one0410** [sunnyhaibin/sunnypilot#127]
2022 Hundai ioniq 5 (soundeast asia model)
In Gap Adjust Cruise setting, I can't switch gap mode from steering wheel but only on touch screen UI.

**Comment by sunnyhaibin** [comment]
- What settings did you have for GAC under "SP - Controls"?
- Was Experimental Mode enabled, or the Experimental icon stay on the top right of the driving screen?

**Comment by one0410** [comment]
![image](https://user-images.githubusercontent.com/11656628/228297768-e2d34cc0-05f2-4546-beb8-13af3e399ed1.png)
and I found that no matter what range I switched from UI.
The range indicator didn't change on the dashboard, it always showed 4 level.

**Comment by sunnyhaibin** [comment]
> ![image](https://user-images.githubusercontent.com/11656628/228297768-e2d34cc0-05f2-4546-beb8-13af3e399ed1.png) and I found that no matter what range I switched from UI. The range indicator didn't change on the dashboard, it always showed 4 level.

If you are on the latest branch, it is because you have "Experimental Mode" set to ON. GAC has zero effect when in Experimental Mode.

**Comment by one0410** [comment]
OK, thanks for your explanation. I'll keep trying.
