### ISSUE TITLE
2023 Santa Fe HEV support

### ISSUE THREAD

**Issue by wileytom65** [sunnyhaibin/sunnypilot#130]
To support 2023 Santa Fe HEV, add the following lines to values.py

transmission:
b'\xf1\x8795441-3D120\x00\xf1\x89E16\x00\x00\x00\x00\x00\x00\x00\xf1\x82TTM2H16SA3',

engine
b'\xf1\x87391312MTL0',

**Comment by sunnyhaibin** [comment]
Please open a PR against [`master`](https://github.com/commaai/openpilot) branch of comma.ai's openpilot to add support for your car. All merged PRs with openpilot will be brought over to sunnypilot.
