### ISSUE TITLE
LTA unavailable warning sound after unplug power from comma

### ISSUE THREAD

**Issue by Shawnfoto** [sunnyhaibin/sunnypilot#143]
Version: 8.14
Model: Prius Prime 22"

Hi, 
I take comma off because I don't want to leave expensive items in the car.
If I turn off my car and unplug USB-C from comma, it will show LTA unavailable warning sound.
But if turn off car for a while, and unplug it, it won't show and alert it.

**Comment by dbzx6r** [comment]
I believe this is by design, you can just ignore it. This also seems like something for the main OpenPilot github: https://github.com/commaai/openpilot

**Comment by sunnyhaibin** [comment]
Try installing the latest `dev` branches and see if this issue can be replicated. Per @dbzx6r 's suggestion, see if this issue is also replicable with stock openpilot installed. Feel free to comment to reopen the issue if the issue persists with the latest branches.
