### ISSUE TITLE
loggerd gpxd process errors

### ISSUE THREAD

**Issue by jonlove234** [sunnyhaibin/sunnypilot#149]
![PXL_20230412_134414152](https://user-images.githubusercontent.com/123476466/231569767-f671c7be-4896-4f24-9181-677784663e10.jpg)
![PXL_20230412_134417272](https://user-images.githubusercontent.com/123476466/231569769-cae1bbd8-66e4-4d63-a4f7-2c45c7efa011.jpg)

Sharing some trace info for these errors

**Comment by sunnyhaibin** [comment]
This error can be fixed by running the following command in SSH:
```bash
sudo mount -o rw,remount /
```

Feel free to comment to reopen the issue if the error persists after running the command.
