### ISSUE TITLE
Volkswagen not mentioned in supported cars

### ISSUE THREAD

**Issue by IanVS** [sunnyhaibin/sunnypilot#150]
Hi I was checking out your fork deciding whether it could be a good fit on my 2019 VW Golf.  I saw that it's not in the list of manufacturers at the top of the README, but there is mention of some features like custom stock longitudinal control working for VW MQB.  So I'm a little bit confused, is there support for my golf, or is it not recommended?  Cheers!

**Comment by dbzx6r** [comment]
Please review the stock OpenPilot wiki: https://github.com/commaai/openpilot/wiki/Volkswagen

**Comment by dbzx6r** [comment]
Just load up the fork and give it a go, worst that can happen is it doesn't work

**Comment by IanVS** [comment]
I did, it works well.

**Comment by IanVS** [comment]
I see this is marked as completed, but the readme still says:

sunnypilot is recommended to be used for most of the following car makes' models:

Hyundai/Kia/Genesis (HKG)
Honda/Acura
Toyota/Lexus
Subaru
Chrysler/Jeep/RAM (FCA)
General Motors (GM)

Is there a reason not to include VW in that list?

**Comment by sunnyhaibin** [comment]
The README is being refactored at the moment, but please feel free to make a PR for the time being to add Volkswagen on there :)
