### ISSUE TITLE
Lkas error when going into reverse

### ISSUE THREAD

**Issue by Miniz199922** [sunnyhaibin/sunnypilot#153]
Sometimes I get lkas error on jeep when going into reverse. Maybe disable acc when reverse then re enable in drive.

**Comment by sunnyhaibin** [comment]
Can you provide the branch you installed and a route with the issue logged?

**Comment by sunnyhaibin** [comment]
Please install the latest `release-c3` to test if this issue is resolved. Feel free to open this issue if it still persists in the latest release.

**Comment by Miniz199922** [comment]
Will do. Thanks.
