### ISSUE TITLE
mazda cx5 2023 longitudinal control is not working

### ISSUE THREAD

**Issue by lijianw2** [sunnyhaibin/sunnypilot#184]
### Describe the bug

Custom ACC can be toggled but it doesn't seem to change the behavior of stock ACC on Mazda CX5 2023. 
Also, experimental mode cannot be toggled. 

### Which car does this affect?

Mazda CX-5 2023

### Provide a route where the issue occurs

n/a

### openpilot version

0.9.2

**Comment by sunnyhaibin** [comment]
Does this car auto-resume with stock openpilot? Experimental Mode is not supported with Custom Stock Longitudinal Control at the moment.

**Comment by sunnyhaibin** [comment]
Please feel free to reopen the issue or reach out to us directly in the [sunnypilot discord](https://discord.sunnypilot.com) if this issue persists in the latest `release-c3` branch.
