### ISSUE TITLE
Ford/Tesla missing car controller "c" when they call `create_common_events()`

### ISSUE THREAD

**Issue by twilsonco** [sunnyhaibin/sunnypilot#185]
### Describe the bug

A car control objected is expected in the `create_common_events()` function but missing from the call for Ford and Tesla. That argument is not in the `create_common_events` definition in Comma master.
![Screenshot 2023-06-17 at 9 03 07 AM](https://github.com/sunnyhaibin/sunnypilot/assets/7284371/c3a013a2-10ce-4d4b-a58d-d6d9cff24dbb)

Here's the thrown exception on a ford maverick
![exception](https://media.discordapp.net/attachments/1098664354628509737/1119624978535567380/PXL_20230617_134943320.jpg?width=611&height=460)

### Provide a route where the issue occurs

foo

### openpilot version

SP 0.9.2.2

**Comment by sunnyhaibin** [comment]
Thanks for the report. Ford is being tracked and worked on at the moment; Tesla is currently not supported and should be behind dashcam mode upstream. I will send out an update on the sunnypilot Discord server when it is ready for Ford users to test.

**Comment by sunnyhaibin** [comment]
This issue has been resolved in the latest `dev-c3`, and will make its way to `staging-c3` and `release-c3`.
