### ISSUE TITLE
Toyota/Lexus - Enhanced Speed Control - ACC speed setting

### ISSUE THREAD

**Issue by markhatchell** [sunnyhaibin/sunnypilot#187]
Hello, Thanks for a great version of openpilot with wonderful features!

I was curious if there were plans to expand the Enhanced Speed Control to Toyota/Lexus models.

I can help test if needed.

Car Make: Lexus
Car Model: NX300
Car Year: 2018
Hardware: Comma Three

Thanks,
Mark

**Comment by sunnyhaibin** [comment]
Enhanced Speed Control works on all Toyota/Lexus platforms that use openpilot longitudinal control. It seems that your car by default uses stock Toyota longitudinal control. According to [CARS.md](https://github.com/commaai/openpilot/blob/master/docs/CARS.md), You will need to install the [smartDSU](https://github.com/commaai/openpilot/wiki/Smart-DSU) to enable openpilot longitudinal control on your car.

![image](https://github.com/sunnyhaibin/sunnypilot/assets/47793918/69ca21f8-95cb-4cef-93d9-a6102ab1c0f4)
![image](https://github.com/sunnyhaibin/sunnypilot/assets/47793918/04655c3e-238f-440e-bbd9-805fe7d6defb)

**Comment by markhatchell** [comment]
Thanks for the reply. I had found the smartDSU hardware as being a requirement for actual longitudinal control however, I was under the impression that the enhanced speed control feature sent messages to the cars stock ACC to adjust the speed setting letting the stock system still do longitudinal control. That is what I was asking about getting working.

**Comment by sunnyhaibin** [comment]
> Thanks for the reply. I had found the smartDSU hardware as being a requirement for actual longitudinal control however, I was under the impression that the enhanced speed control feature sent messages to the cars stock ACC to adjust the speed setting letting the stock system still do longitudinal control. That is what I was asking about getting working. 

Enhanced Speed Control requires openpilot longitudinal control or Custom Stock Longitudinal Control. Toyota/Lexus currently is not compatible with Custom Stock Longitudinal Control. For this platform, the best option is to install smartDSU and to allow openpilot longitudinal control to use Enhanced Speed Control.
