### ISSUE TITLE
Steering temporarily unavailable in low speed

### ISSUE THREAD

**Issue by otaviobonder-deel** [sunnyhaibin/sunnypilot#223]
### Describe the bug

When I have lateral enabled, comes to a complete stop and quickly let the car roll forward. I get the `STEERING TEMPORARILY UNAVAILABLE` and I can't reengange until I turn off and on the car. I also get the `TAKE CONTROL IMMEDIATELY`. I tried with `dev-c3` and `staging-c3`, both have the same issue.

I don't have an official device (I'm using Mr.One clone), so I can't upload the logs to comma, but here are them: https://drive.google.com/drive/folders/1LBR7k8OQbNT3fRMk9xr8j5WiCA9X5g0z?usp=sharing

### Which car does this affect?

VW Taos 2023

### Provide a route where the issue occurs

https://drive.google.com/drive/folders/1LBR7k8OQbNT3fRMk9xr8j5WiCA9X5g0z?usp=sharing

### openpilot version

d64b95d36d762dc367fa517033d3c7be87020d09

**Comment by sunnyhaibin** [comment]
This seems to be a known issue with stock openpilot as well:
- https://github.com/commaai/openpilot/issues/30495

You should continue monitoring the issue linked. sunnypilot will merge any fixes that are merged in upstream if this is resolved in the future.
