### ISSUE TITLE
 Cluster screen in HDA2 vehicle (hyundai, kia, genesis)

### ISSUE THREAD

**Issue by PharmeRx78** [sunnyhaibin/sunnypilot#228]
I am using sunnypilot well in EV6. thank you

This is an opinion regarding the discrepancy in the cluster screen under HDA2 operating conditions.

![99EE4C4E5E7AE53B28 (1)](https://github.com/sunnyhaibin/sunnypilot/assets/144088989/a6580195-d4c3-4fb1-833b-5aef57ff3d06)

![99EE4C4E5E7AE53B28](https://github.com/sunnyhaibin/sunnypilot/assets/144088989/278ce698-2d18-4a53-be4a-714a23f7ad37)

Can the curvature expression be improved on the cluster screen?

**Comment by sunnyhaibin** [comment]
The messages/signals with these UI elements from the car's cluster are not yet defined in the DBC to date. These messages/signals will need to be reverse-engineered. Someone with reverse engineering experiences with or without a CAN-FD platform of Hyundai/Kia/Genesis will need to work on this. We currently do not have plans to work on this, but a bounty can be setup on fundraising platform such as [GoFundMe](https://www.gofundme.com/).
