### ISSUE TITLE
Add Toggle for enabling Tethering on boot

### ISSUE THREAD

**Issue by khoi** [sunnyhaibin/sunnypilot#42]
People outside US are likely to have an unlimited/unthrottled data plan, and using Comma device for sharing network would be great

**Comment by wallneradam** [comment]
I've created a service (systemd), which enables hotspot, when the car has lost WIFI connection, then disables it when the car is near home (by GPS).

If you interested I can share the code. It is not integrated into Openpilot UI, it is a python service, with a systemd unit file. And the home (and/or work) coordinates can be set with a constants. Though it can be integrated, just it was good for me.

**Comment by khoi** [comment]
do share it please @wallneradam

**Comment by sunnyhaibin** [comment]
This will be added in sunnypilot 0.8.14-2. Thanks for the suggestion!
