### ISSUE TITLE
Disable Onroad Uploads: Detail Clarification

### ISSUE THREAD

**Issue by C0mpl3t3N00b** [sunnyhaibin/sunnypilot#71]
**Problem:** 

The phrase "_Turn on_" in the context of a toggle and its label including"_**Disable**_" aren't clear.

**Reference:**

What is written in the ReadMe:
`**Disable Onroad Uploads** - Disable uploads completely when onroad. Necessary to avoid high data usage when connected to Wi-Fi hotspot.`

What is written on device in the SP-General Menu:
`**Disable Onroad Uploads** - Disable uploads completely when onroad. Necessary to avoid high data usage when connected to Wi-Fi hotspot. Turn on this feature if you are looking to utilize map-based features, such as Speed Limit Control (SLC) and Map-based Turn Speed Control (MTSC).`

**Suggestion:** 

`**Disable Onroad Uploads** - Disable uploads completely when onroad. Necessary to avoid high data usage when connected to Wi-Fi hotspot. Do not enable this toggle if you are looking to utilize map-based features, such as Speed Limit Control (SLC) and Map-based Turn Speed Control (MTSC).`

**Assumptions:** 

1. Onroad Uploads are a hard requirement for Map-based features

2. Map-based features, in nature will result in higher bandwidth/data usage

**Comment by sunnyhaibin** [comment]
Thanks for the suggestion. This makes more sense than what I had before. I'll have it updated with the suggested text.

Thanks! :)
