### ISSUE TITLE
Honda crv 2021 car unrecognised 

### ISSUE THREAD

**Issue by gilgamesh0808** [sunnyhaibin/sunnypilot#77]
As title, after I install 0.8.12-prod-full-honda, and it showed car unrecognised

**Comment by Moodkiller** [comment]
Do you have a C3 by chance? Best to install [0.8.14-prod-c3](https://github.com/sunnyhaibin/sunnypilot/tree/0.8.14-prod-c3)

**Comment by gilgamesh0808** [comment]
Sorry but I'm using C2 model

**Comment by sunnyhaibin** [comment]
You should be able to select your car under the "Vehicles" menu. If it is still an ongoing issue, please feel free to open another issue. Thanks!
