### ISSUE TITLE
GM: controls failed on startup

### ISSUE THREAD

**Issue by twilsonco** [sunnyhaibin/sunnypilot#80]
Caused by subscripting the car state cruise buttons. Fixed here https://github.com/twilsonco/openpilot/commit/16054d0087d37d6e4ecf539119d2b4c35a00fa83

**Comment by sunnyhaibin** [comment]
Seems to be fixed in the latest [`test-c3`](https://github.com/sunnyhaibin/sunnypilot/tree/test-c3) branch. Thanks!
