### ISSUE TITLE
Kia EV6 getting CAN error on test-c3 branch

### ISSUE THREAD

**Issue by alenl2** [sunnyhaibin/sunnypilot#87]
When switching back to test-c3-apollo branch it works fine but something brakes with test-c3.

Error logs show "0x1FA NOT SEEN" from opendbc/can/parser.cc

**Comment by alenl2** [comment]
It has something to do with reading the speed limit.

Commenting out these 2 lines fixes the parser

https://github.com/sunnyhaibin/sunnypilot/blob/f34deb644419752d8ba7d50f794901c0341674d7/selfdrive/car/hyundai/carstate.py#L857
https://github.com/sunnyhaibin/sunnypilot/blob/f34deb644419752d8ba7d50f794901c0341674d7/selfdrive/car/hyundai/carstate.py#L858

**Comment by sunnyhaibin** [comment]
@alenl2 Does your EV6 have HDA1, HDA2, or no HDA? Can you share a route from your car?

> • Share your device with me (https://connect.comma.ai/, gear icon, share by email, sunnyhaibin@gmail.com, share icon again to confirm), set the device name to your year/make/model and your Discord username (with #xxxx) so I can find it in the list.

Feel free to reach out to me in the sunnypilot discord server's #test-feedback channel to continue.

**Comment by alenl2** [comment]
It's HDA2 car but looks like the latest branch (test-c3-20221207) fixe the issue.
