### ISSUE TITLE
Toyota Corolla 2019 (Comma 3)

### ISSUE THREAD

**Issue by autorun1992** [sunnyhaibin/sunnypilot#90]
![20221203_185136](https://user-images.githubusercontent.com/16954195/205469198-d90d1655-86e5-4ca9-94a7-9c26ba95ebb5.jpg)
![20221203_185141](https://user-images.githubusercontent.com/16954195/205469209-b1852b3c-184e-44fc-a746-590323785164.jpg)

I used this installer.comma.ai/sunnyhaibin/test-c3

Manager failed to start

Traceback(most recent call last):
File"<frozen importlib._bootstrap >,line 219, in

**Comment by sunnyhaibin** [comment]
Try to [factory reset](https://commasupport.zendesk.com/hc/en-us/articles/4413447038103-Performing-a-Factory-Reset#:~:text=Reset%20the%20comma%20three%20by,reset%20screen%20will%20come%20up.) and reinstall with the same URL. A reinstall usually fixes this issue. Feel free to reopen the issue if you continue to see this error.

Thanks!

**Comment by Sliicy** [comment]
For anyone in the future that needs help, the link mentioned above is dead so just head to [flash.comma.ai](https://flash.comma.ai) and follow the steps there to reflash your device and factory reset it.
