### ISSUE TITLE
Red / Green light chime on chill-mode only cars

### ISSUE THREAD

**Issue by Metalbird1997** [sunnyhaibin/sunnypilot#92]
Could you make it possible to enable the "experimental mode" toggle in settings for unsupported cars? My car does not support OP e2e long, so I cannot enable experimental mode. It's simply greyed out. I'd still like to use the red/green light chime that was added in 20221207. Or maybe enable the chime and indicator toggles regardless of experimental mode.

Thanks, keep up the good work!

**Comment by sunnyhaibin** [comment]
Something is in the works for all cars, so stay tuned in the discord server!
