### ISSUE TITLE
SLC not working for Kia K5 Hybrid (2020)

### ISSUE THREAD

**Issue by PLV50VL7R3** [sunnyhaibin/sunnypilot#97]
Hi. I'm using C3 with Kia K5 Hybrid (2020). It has HDA1 feature, however SLC is not working.

I selected "Hyundai Sonata Hybrid 2020-22", and added fingerprint of the car on the values.py:
FINGERPRINTS = {
  CAR.SONATA_HYBRID: [{
    127: 8, 304: 8, 320: 8, 339: 8, 352: 8, 356: 4, 516: 8, 544: 8, 576: 8, 593: 8, 688: 6, 757: 2, 832: 8, 881: 8, 882: 8, 897: 8, 902: 8, 903: 8, 905: 8, 909: 8, 913: 8, 916: 8, 919: 8, 1040: 8, 1042: 8, 1056: 8, 1057: 8, 1078: 4, 1096: 8, 1102: 8, 1114: 8, 1136: 6, 1138: 5, 1151: 8, 1155: 8, 1156: 8, 1157: 4, 1162: 8, 1164: 8, 1168: 8, 1173: 8, 1180: 8, 1184: 8, 1186: 2, 1191: 2, 1193: 8, 1210: 8, 1225: 8, 1227: 8, 1265: 4, 1280: 8, 1287: 4, 1290: 8, 1291: 8, 1292: 8, 1294: 8, 1312: 8, 1322: 8, 1330: 8, 1339: 8, 1342: 8, 1343: 8, 1345: 8, _**1348: 8**_, 1355: 8, 1363: 8, 1369: 8, 1371: 8, 1378: 8, 1379: 8, 1407: 8, 1419: 8, 1427: 6, 1429: 8, 1430: 8, 1446: 8, 1448: 8, 1456: 4, 1460: 8, 1470: 8, 1476: 8, 1485: 8, 1535: 8
  }],
 ...
(Checked that it has 0x544 in the fingerprint)

Thanks.

**Comment by sunnyhaibin** [comment]
Hello, is this car supported in upstream openpilot? If not already, I recommend reaching out to me in the comma Discord server #hyundai-kia-genesis channel and work on officially supporting this car.

Once complete, it can be easily supported in sunnypilot.
