### ISSUE TITLE
Cruise fault on Bolt euv on pressing resume 

### ISSUE THREAD

**Issue by ServerDummy** [sunnyhaibin/sunnypilot#99]
Cruise fault will happen anytime pressing resume button with acc while at a standstill, will not happen if I tap the gas(will resume perfectly fine if I do). Car will jerk a little before engaging the breaks, and even sometimes the parking brake if you continue to press resume. On stock open pilot it will just say cannot resume below 3mph and give no faults.

[Example on Sunny](https://youtu.be/-OQv2AocmUI)

**Comment by sunnyhaibin** [comment]
This issue should be fixed in the latest sunnypilot `test` or `dev` branches. Please feel free to open a new issue if it still exists.
